Updated main.yml with -L handling http 3xx redirects

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,5 +8,5 @@ jobs:
       - name: Ping DB through app
         run: |
           echo "Starting curl test..." 
-          curl -sf hangman-3x9r.onrender.com || echo "⚠️ Ping failed!"
+          curl -sfL hangman-3x9r.onrender.com || echo "⚠️ Ping failed!"
           echo "Curl test complete!"
